// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"github.com/labstack/echo/v4"
)

// Point defines model for Point.
type Point struct {
	Lat  *float32 `json:"lat,omitempty"`
	Lon  *float32 `json:"lon,omitempty"`
	Name *string  `json:"name,omitempty"`
}

// RouteRequest defines model for RouteRequest.
type RouteRequest struct {
	Interests     *[]string `json:"interests,omitempty"`
	Lat           float32   `json:"lat"`
	Lon           float32   `json:"lon"`
	MaxDistanceKm *float32  `json:"max_distance_km,omitempty"`
}

// RouteResponse defines model for RouteResponse.
type RouteResponse struct {
	DistanceKm *float32 `json:"distance_km,omitempty"`
	Points     *[]Point `json:"points,omitempty"`
}

// GenerateRouteJSONRequestBody defines body for GenerateRoute for application/json ContentType.
type GenerateRouteJSONRequestBody = RouteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Generate route
	// (POST /routes/generate)
	GenerateRoute(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GenerateRoute converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateRoute(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GenerateRoute(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/routes/generate", wrapper.GenerateRoute)

}
